export const enKeys = {
  weighingSchema: 'Weighing Schema',
  packetCount: 'Packet Count',
  bookId: 'Book Id',
  bookDate: 'Book Date',
  bookTime: 'Book Time',
  companyName: 'Company Name',
  carrierName: 'Carrier Name',
  mobilePhone: 'Mobile Phone',
  truckPlate: 'Truck Plate',
  transportOrderNumber: 'Transport Order Number',
  chargennummer: 'Chargennummer',
  abmessungen: 'Abmessungen',
  weightTon: 'Weight Ton',
  supplier: 'Supplier',
  checkedIn: 'Checked In',
  xNumber: 'X-Number',
  firstWeighing: 'First Weighing',
  secondWeighing: 'Second Weighing',
  differenceWeighing: 'Difference Weighing',
  unloadingBegin: 'Unloading Begin',
  unloadingBeginDriver: 'Unloading Begin - Driver',
  unloadingEnd: 'Unloading End',
  unloadingEndDriver: 'Unloading End - Driver',
  checkedOut: 'Checked out',
  weightInTon: 'Weight in ton',
  packingListOk: 'Packing List OK',
  materialOk: 'Material OK',
  comment: 'Comment',
  uploadPic: 'Upload pic',
  timeStamp: 'Timestamp',
  commentContent: 'Comment Content',
  commentDate: 'Comment Date',
  commentAuthor: 'Sender',
  processStepFirstWeighing: 'First Weighing',
  processStepPackingListCheck: 'Packing List Check',
  processStepUnloadingBegin: 'Unloading Begin',
  processStepMaterialCheck: 'Material check',
  processStepUnloadingBeginDriver: 'Unloading Begin Driver',
  processStepUnloadingEnd: 'Unloading End',
  processStepUnloadingEndDriver: 'Unloading End - Driver',
  processStepSecondWeighing: 'Second Weighing',
  grossWeight: 'Gross Weight',
  differenceDeviation: 'Difference Deviation (%)',

  workflowName: 'Yard'
};
