export const deKeys = {
  weighingSchema: 'Weighing Schema in german',
  packetCount: 'Anzahl der Packstücke (list)',
  bookId: 'Buchungs-ID',
  bookDate: 'Buchungsdatum',
  bookTime: 'Buchungsuhrzeit',
  companyName: 'Firmenname',
  carrierName: 'Name des Frachtführers',
  mobilePhone: 'Mobiltelefon',
  truckPlate: 'LKW-Kennzeichen',
  transportOrderNumber: 'Transportauftragsnummer',
  chargennummer: 'Chargennummer',
  abmessungen: 'Abmessungen',
  weightTon: 'Gewicht (to)',
  supplier: 'Lieferant',
  checkedIn: 'Angemeldet',
  xNumber: 'X-Nummer',
  firstWeighing: 'Erste Verwiegung',
  secondWeighing: 'Zweite Verwiegung',
  differenceWeighing: 'Differenzverwiegung',
  unloadingBegin: 'Entladebeginn',
  unloadingBeginDriver: 'Entladebeginn - Fahrer',
  unloadingEnd: 'Entladeende',
  unloadingEndDriver: 'Entladeende - Fahrer',
  checkedOut: 'Abgemeldet',
  weightInTon: 'Gewicht in Tonnen',
  packingListOk: 'Packliste i.O.',
  materialOk: 'Material i.O.',
  comment: 'Kommentar',
  uploadPic: 'Bild hochladen',
  timeStamp: 'Zeitstampel',
  commentContent: 'Kommentarinhalte',
  commentDate: 'Kommentardatum',
  commentAuthor: 'Sender',
  processStepFirstWeighing: 'Erste Verwiegung',
  processStepPackingListCheck: 'Packliste überprüfen',
  processStepUnloadingBegin: 'Entladebeginn',
  processStepMaterialCheck: 'Material überprüfen',
  processStepUnloadingBeginDriver: 'Entladebeginn - Fahrer',
  processStepUnloadingEnd: 'Entladeende',
  processStepUnloadingEndDriver: 'Entladeende - Fahrer',
  processStepSecondWeighing: 'Zweite Verwiegung',
  grossWeight: 'Gesamtgewicht',
  differenceDeviation: 'Differenzabweichung (%)',

  workflowName: 'Wareneingang'
};
